### ISSUE TITLE
Cannot select item.

### ISSUE THREAD

**Issue by ljaniszewski** [ajalt/flexadapter#2]
I use `adapter.setHasStableIds(true)`

but when I long click on item, this happens:
`Java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
     ViewHolder 1:ViewHolder{936d7aa position=0 id=-1, oldPos=-1, pLpos:-1} 
     View Holder 2:ViewHolder{4f3bd32 position=2 id=-1, oldPos=-1, pLpos:-1} android.support.v7.widget.RecyclerView{aaa160c VFED..... .F....ID 0,0-850,768 #7f08007f app:id/product_list_recycler_view}, adapter:com.github.ajalt.flexadapter.FlexAdapter@66b3b55, layout:android.support.v7.widget.StaggeredGridLayoutManager@7a596a`

this is my item: 

```
data class ProductItem(
    private val model: ProductItemModel,
    private val onLongClickListener: OnLongClickListener? = null
) : FlexAdapterSelectableExtensionItem(R.layout.product_item_view) {

    override fun bindItemView(itemView: View, selected: Boolean, position: Int) {
        itemView.setOnLongClickListener {
            onLongClickListener?.onLongClick(this)
            true
        }
        if (selected) {
            itemView.alpha = 0.5f
        } else {
            itemView.alpha = 1f
        }
        itemView.price.text = model.productPrice
        itemView.price_usd.text = model.productPriceUSD
        if (itemView.product_image.drawable == null){
            Picasso.get().load(model.productPicture).into(itemView.product_image)
        }
        itemView.name.text = model.productName
    }
}
```

I cannot figure out how this adapter is supposed to work. 
All I need is to make the item selectable, show that it is selected when long click, and possibly move item around to change the product order. 

I tried to use setStableIds because I had issues of items jumping around whenever trying to select them and change their background alpha, so I set this to true, but it didn't help. 

I don't see any special code in your sample but it works, and my code doesnt. 
any suggestions?

**Comment by ajalt** [comment]
Support for stable ids is not in the latest release. You can use a snapshot build to get that functionality:

```gradle
implementation 'com.github.ajalt:flexadapter:25191c2edc'
```

Let me know if it's still a problem in the snapshot.
